This notebook flattens displays and actions to vectors, so we can do supervised and rl learning on it

In [1]:
import pandas as pd
import json
#import pyreact_core.query.displays as qd
#import pyreact.query.packets as qp
import operator
import json
import numpy as np
import scipy as sp

from gym_ianna.envs.ianna_env import get_state_rep_from_dicts, get_keys

In [2]:

actions = pd.read_csv('experts_dataset/experts_actions.tsvv', sep = '\t', escapechar='\\')
displays = pd.read_csv('experts_dataset/experts_displays.tsv', sep = '\t', escapechar='\\')

In [3]:
displays.head()

,Unnamed: 0,display_id,session_id,subsession_id,display_number,data_summary,filtering,sorting,grouping,aggregations,projected_fields,session_id.1,user_id,project_id,curr_display_id,size,solution,data_layer,granularity_layer
0,0,1,1,NaN,NaN,"{""info_line"":[0.0015997002,8149],""eth_dst"":[0....","{""list"": []}","{""list"":[]}","{""list"":[]}",null,"{""list"":[{""field"":""number""},{""field"":""sniff_ti...",1,1,1,NaN,NaN,"{""solution"":""I AM BEAUTIFUL!!!!!!!"",""project_i...","{""eth_dst"": {""unique"": 0.00023126734505087883,...",null
1,1,2,1,NaN,NaN,"{""info_line"":[0.0015997002,8149],""eth_dst"":[0....","{""list"": []}","{""list"":[]}","{""list"":[{""field"":""eth_src"",""groupPriority"":0}]}",null,"{""list"":[{""field"":""number""},{""field"":""sniff_ti...",1,1,1,NaN,NaN,"{""solution"":""I AM BEAUTIFUL!!!!!!!"",""project_i...","{""eth_dst"": {""unique"": 0.00023126734505087883,...","{""group_attrs"": [""eth_src""], ""agg_attrs"": {}, ..."
2,2,3,1,NaN,NaN,"{""info_line"":[0.0015997002,8149],""eth_dst"":[0....","{""list"": []}","{""list"":[]}","{""list"":[{""field"":""eth_src"",""groupPriority"":0}...",null,"{""list"":[{""field"":""number""},{""field"":""sniff_ti...",1,1,1,NaN,NaN,"{""solution"":""I AM BEAUTIFUL!!!!!!!"",""project_i...","{""eth_dst"": {""unique"": 0.00023126734505087883,...","{""group_attrs"": [""eth_src"", ""ip_src""], ""agg_at..."
3,3,4,2,NaN,NaN,"{""info_line"":[0.0015997002,8149],""eth_dst"":[0....","{""list"": []}","{""list"":[]}","{""list"":[]}",null,"{""list"":[{""field"":""number""},{""field"":""sniff_ti...",2,5,1,NaN,NaN,"{""solution"":""Port Scan, if target answers ping...","{""eth_dst"": {""unique"": 0.00023126734505087883,...",null
4,4,5,2,NaN,NaN,"{""info_line"":[0.0015997002,8149],""eth_dst"":[0....","{""list"": []}","{""list"":[]}","{""list"":[{""field"":""eth_src"",""groupPriority"":0}]}","{""list"": [{""field"": ""length"", ""type"": ""avg""}]}","{""list"":[{""field"":""number""},{""field"":""sniff_ti...",2,5,1,NaN,NaN,"{""solution"":""Port Scan, if target answers ping...","{""eth_dst"": {""unique"": 0.00023126734505087883,...","{""group_attrs"": [""eth_src""], ""agg_attrs"": {}, ..."

In [9]:
all_vectors = []
def flatten_row_to_vector(row):
    data_layer = json.loads(row['data_layer'])
    granularity_layer = json.loads(row['granularity_layer'])
    res = [row['display_id']]
    res.extend(get_state_rep_from_dicts(data_layer, granularity_layer))
    all_vectors.append(res)

displays.apply(flatten_row_to_vector, axis = 1)
X = pd.DataFrame(all_vectors)
X.rename(columns={0: 'display_id'}, inplace=True)

In [20]:
print(X.shape)
X.head()

(1109, 52)

,display_id,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,49,50,51
0,1,0.034416,0.034416,0.039079,0.98829,0.85059,0.086827,0.054094,1.0,0.523395,...,0,0,0,0,0,0,0,0,0,0
1,2,0.034416,0.034416,0.039079,0.98829,0.85059,0.086827,0.054094,1.0,0.523395,...,0,0,0,0,0,0,0,0,0,0
2,3,0.034416,0.034416,0.039079,0.98829,0.85059,0.086827,0.054094,1.0,0.523395,...,0,0,0,1,0,0,0,0,0,0
3,4,0.034416,0.034416,0.039079,0.98829,0.85059,0.086827,0.054094,1.0,0.523395,...,0,0,0,0,0,0,0,0,0,0
4,5,0.034416,0.034416,0.039079,0.98829,0.85059,0.086827,0.054094,1.0,0.523395,...,0,0,0,0,0,0,0,0,0,0

In [11]:
actions.head()

,action_id,action_number,action_params,session_id,subsession_id,action_type,creation_time,parent_display_id,child_display_id,session_id.1,user_id,project_id,curr_display_id,size,solution
0,1,NaN,"{""field"":""eth_src"",""aggregations"":[],""groupPri...",1,NaN,group,2016-08-14 12:44:05,1,2,1,1,1,NaN,NaN,"{""solution"":""I AM BEAUTIFUL!!!!!!!"",""project_i..."
1,2,NaN,"{""field"":""ip_src"",""aggregations"":[],""groupPrio...",1,NaN,group,2016-08-14 12:44:08,2,3,1,1,1,NaN,NaN,"{""solution"":""I AM BEAUTIFUL!!!!!!!"",""project_i..."
2,3,NaN,"{""field"":""eth_src"",""aggregations"":[{""field"":""l...",2,NaN,group,2016-08-15 09:40:42,4,5,2,5,1,NaN,NaN,"{""solution"":""Port Scan, if target answers ping..."
3,4,NaN,"{""field"":""ip_src"",""aggregations"":[{""field"":""le...",2,NaN,group,2016-08-15 13:13:54,4,6,2,5,1,NaN,NaN,"{""solution"":""Port Scan, if target answers ping..."
4,5,NaN,"{""field"":""ip_src"",""aggregations"":[],""groupPrio...",2,NaN,group,2016-08-15 13:14:10,4,7,2,5,1,NaN,NaN,"{""solution"":""Port Scan, if target answers ping..."

In [27]:
actions.action_params.head(1)[0]

'{"field":"eth_src","aggregations":[],"groupPriority":0}'

In [24]:
recs = []

def get_groupby_field_label(x):
    action = json.loads(x)
    if "groupPriority" not in action:
        return -1
    field_name = action["field"]
    field_id = get_keys().index(field_name)
    return field_id

actions.loc[:, 'group_by_field_label'] = actions.action_params.apply(get_groupby_field_label)

y = actions[actions.label != -1][['parent_display_id', 'label']]

In [25]:
print(y.shape)
y.head()

(503, 2)

   parent_display_id  label
0                  1      1
1                  2      5
2                  4      1
3                  4      5
4                  4      5

In [23]:
X.to_csv('experts_dataset/x.tsv', sep = '\t', escapechar='\\', index = False)
y.to_csv('experts_dataset/y.tsv', sep = '\t', escapechar='\\', index = False)